const REPO = 'Putrajayarblx/putrajaya-of-roblox';
const BRANCH = 'main';
const RAW_BASE = `https://raw.githubusercontent.com/${REPO}/${BRANCH}/`;

const escapeHTML = (value = '') => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const slugify = value => String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const formatDate = value => { if (!value) return 'Unpublished'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('en-MY', {day:'numeric', month:'short', year:'numeric'}).format(date); };
const parseFrontmatter = markdown => { const match = String(markdown).match(/^---\s*([\s\S]*?)\s*---\s*([\s\S]*)$/); if (!match) return {meta:{}, body:String(markdown).trim()}; const meta = {}; match[1].split('\n').forEach(line => { const split = line.match(/^([\w-]+):\s*(.*)$/); if (split) meta[split[1]] = split[2].trim().replace(/^['"]|['"]$/g, ''); }); return {meta, body:match[2].trim()}; };
const inlineMarkdown = value => escapeHTML(value).replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1">').replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/`([^`]+)`/g, '<code>$1</code>');
const markdownToHTML = markdown => String(markdown || '').split(/\n\s*\n/).map(block => { const text = block.trim(); if (!text) return ''; if (/^#{1,3}\s/.test(text)) { const match = text.match(/^(#{1,3})\s+(.+)$/); const level = match[1].length; return `<h${level}>${inlineMarkdown(match[2])}</h${level}>`; } if (text.startsWith('> ')) return `<blockquote>${inlineMarkdown(text.slice(2))}</blockquote>`; if (/^[-*]\s/.test(text)) return `<ul>${text.split('\n').map(item => `<li>${inlineMarkdown(item.replace(/^[-*]\s/, ''))}</li>`).join('')}</ul>`; return `<p>${inlineMarkdown(text).replace(/\n/g, '<br>')}</p>`; }).join('');
const imageURL = value => { if (!value) return ''; if (/^https?:\/\//.test(value)) return value; return value.startsWith('/') ? value : `${RAW_BASE}${value}`; };
const loadEntries = async folder => { const response = await fetch(`${RAW_BASE}${folder}/`, {cache:'no-store'}); if (!response.ok) throw new Error(`Unable to load ${folder}`); return []; };
const loadFolder = async folder => { const api = await fetch(`https://api.github.com/repos/${REPO}/contents/${folder}?ref=${BRANCH}`, {headers:{Accept:'application/vnd.github+json'}, cache:'no-store'}); if (!api.ok) throw new Error('Content index unavailable'); const files = (await api.json()).filter(file => file.type === 'file' && file.name.endsWith('.md')); return Promise.all(files.map(async file => { const response = await fetch(`${RAW_BASE}${file.path}`, {cache:'no-store'}); if (!response.ok) throw new Error(`Unable to load ${file.name}`); const parsed = parseFrontmatter(await response.text()); return {...parsed.meta, body:parsed.body, slug:file.name.replace(/\.md$/, '')}; })); };
const renderError = (root, message) => { root.innerHTML = `<div class="content-error"><strong>Content temporarily unavailable.</strong><p>${escapeHTML(message)} Please refresh or try again shortly.</p></div>`; };
const cardImage = entry => entry.image ? `<img class="cms-card-image" src="${escapeHTML(imageURL(entry.image))}" alt="">` : '<div class="cms-card-image cms-placeholder" aria-hidden="true"></div>';
const renderListPage = async type => { const root = document.getElementById(`${type}-list`); if (!root) return; const search = document.getElementById(`${type}-search`); const filter = document.getElementById(`${type}-category`); try { let entries = await loadFolder(`content/${type}`); entries.sort((a,b) => new Date(b.date || 0) - new Date(a.date || 0)); const categories = [...new Set(entries.map(entry => entry[type === 'blog' ? 'category' : 'section']).filter(Boolean))].sort(); categories.forEach(category => { filter.insertAdjacentHTML('beforeend', `<option value="${escapeHTML(category)}">${escapeHTML(category)}</option>`); const side = document.getElementById(`${type}-sidebar-categories`); if (side) side.insertAdjacentHTML('beforeend', `<li><a href="#" data-category="${escapeHTML(category)}">${escapeHTML(category)}</a></li>`); }); const draw = () => { const query = (search.value || '').toLowerCase(); const selected = filter.value; const visible = entries.filter(entry => { const haystack = `${entry.title} ${entry.summary} ${entry.body}`.toLowerCase(); return (!query || haystack.includes(query)) && (!selected || entry[type === 'blog' ? 'category' : 'section'] === selected); }); root.innerHTML = visible.length ? visible.map((entry, index) => type === 'blog' ? `<article class="cms-card ${index === 0 ? 'featured' : ''}">${cardImage(entry)}<div class="cms-card-copy"><p class="post-meta">${escapeHTML(entry.category || 'Community')} <span>•</span> ${formatDate(entry.date)}</p><h2>${escapeHTML(entry.title || 'Untitled')}</h2><p>${escapeHTML(entry.summary || entry.body.replace(/[#>*`]/g, '').slice(0, 150))}</p><p class="byline">By ${escapeHTML(entry.author || 'Putrajaya Editorial Team')}</p><a class="text-link" href="blog-post.html?slug=${encodeURIComponent(entry.slug)}">Read the story <span>↗</span></a></div></article>` : `<article class="wiki-entry"><div class="wiki-entry-number">${String(index + 1).padStart(2, '0')}</div><div><p class="eyebrow">${escapeHTML(entry.section || 'Reference')}</p><h3><a href="wiki-article.html?slug=${encodeURIComponent(entry.slug)}">${escapeHTML(entry.title || 'Untitled')}</a></h3><p>${escapeHTML(entry.summary || entry.body.replace(/[#>*`]/g, '').slice(0, 180))}</p></div><a class="entry-arrow" href="wiki-article.html?slug=${encodeURIComponent(entry.slug)}" aria-label="Read ${escapeHTML(entry.title)}">↗</a></article>`).join('') : '<p class="empty-state">No articles match your search.</p>'; }; search.addEventListener('input', draw); filter.addEventListener('change', draw); document.querySelectorAll(`[data-category]`).forEach(link => link.addEventListener('click', event => { event.preventDefault(); filter.value = link.dataset.category; draw(); })); draw(); } catch (error) { renderError(root, error.message); } };
const renderArticlePage = async type => { const root = document.getElementById('article-root'); if (!root) return; const slug = new URLSearchParams(location.search).get('slug'); if (!slug) { root.innerHTML = '<div class="content-error"><strong>Article not found.</strong><p>Return to the directory to choose an article.</p></div>'; return; } try { const entries = await loadFolder(`content/${type}`); const entry = entries.find(item => item.slug === slug); if (!entry) throw new Error('That article could not be found.'); root.innerHTML = `<article class="cms-article"><a class="back-link" href="${type}.html">← Back to ${type === 'blog' ? 'Blog' : 'Wiki'}</a><p class="eyebrow">${escapeHTML(type === 'blog' ? entry.category || 'Community' : entry.section || 'Reference')}</p><h1>${escapeHTML(entry.title)}</h1><p class="article-meta">${type === 'blog' ? `By ${escapeHTML(entry.author || 'Putrajaya Editorial Team')} · ${formatDate(entry.date)}` : 'Putrajaya of Roblox Wiki'}</p>${entry.image ? `<img class="article-cover" src="${escapeHTML(imageURL(entry.image))}" alt="">` : ''}<div class="article-body">${markdownToHTML(entry.body)}</div></article>`; } catch (error) { renderError(root, error.message); } };
const initializeTheme = () => { const theme = document.querySelector('.theme-toggle'); const saved = localStorage.getItem('putrajaya-theme'); if (saved === 'dark') document.body.classList.add('dark-mode'); if (theme) theme.addEventListener('click', () => { document.body.classList.toggle('dark-mode'); localStorage.setItem('putrajaya-theme', document.body.classList.contains('dark-mode') ? 'dark' : 'light'); }); const menu = document.querySelector('.menu-toggle'); const nav = document.querySelector('.nav-links'); if (menu && nav) menu.addEventListener('click', () => { const open = nav.classList.toggle('open'); menu.setAttribute('aria-expanded', open); }); };
document.addEventListener('DOMContentLoaded', () => { initializeTheme(); renderListPage('blog'); renderListPage('wiki'); renderArticlePage(document.body.dataset.articlePage); });
