const REPO = 'Putrajayarblx/putrajaya-of-roblox';
const BRANCH = 'main';
const API_BASE = `https://api.github.com/repos/${REPO}/contents/`;
const RAW_BASE = `https://raw.githubusercontent.com/${REPO}/${BRANCH}/`;

const escapeHTML = (value = '') => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const formatDate = value => { if (!value) return 'Unpublished'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('en-MY',{day:'numeric',month:'short',year:'numeric'}).format(date); };
const parseFrontmatter = markdown => { const match = String(markdown).match(/^---\s*([\s\S]*?)\s*---\s*([\s\S]*)$/); if (!match) return {meta:{},body:String(markdown).trim()}; const meta={}; match[1].split('\n').forEach(line=>{const item=line.match(/^([\w-]+):\s*(.*)$/);if(item)meta[item[1]]=item[2].trim().replace(/^['"]|['"]$/g,'')});return {meta,body:match[2].trim()}; };
const imageURL = value => { if (!value) return ''; if (/^https?:\/\//.test(value)) return value; return value.startsWith('/') ? value : `${RAW_BASE}${value}`; };
const inlineMarkdown = value => escapeHTML(value).replace(/!\[([^\]]*)\]\(([^)]+)\)/g,'<img src="$2" alt="$1">').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');
const markdownToHTML = markdown => String(markdown||'').split(/\n\s*\n/).map(block=>{const text=block.trim();if(!text)return '';if(/^#{1,3}\s/.test(text)){const m=text.match(/^(#{1,3})\s+(.+)$/);return `<h${m[1].length}>${inlineMarkdown(m[2])}</h${m[1].length}>`}if(text.startsWith('> '))return `<blockquote>${inlineMarkdown(text.slice(2))}</blockquote>`;if(/^[-*]\s/.test(text))return `<ul>${text.split('\n').map(item=>`<li>${inlineMarkdown(item.replace(/^[-*]\s/,''))}</li>`).join('')}</ul>`;return `<p>${inlineMarkdown(text).replace(/\n/g,'<br>')}</p>`}).join('');
const loadFolder = async folder => { const response=await fetch(`${API_BASE}${folder}?ref=${BRANCH}`,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'}); if(!response.ok)throw new Error(`Unable to load ${folder}`); const files=(await response.json()).filter(file=>file.type==='file'&&file.name.endsWith('.md')); return Promise.all(files.map(async file=>{const raw=await fetch(`${RAW_BASE}${file.path}`,{cache:'no-store'});if(!raw.ok)throw new Error(`Unable to load ${file.name}`);const parsed=parseFrontmatter(await raw.text());return {...parsed.meta,body:parsed.body,slug:file.name.replace(/\.md$/,'')};})); };
const renderError=(root,message)=>{root.innerHTML=`<div class="content-error"><strong>Content temporarily unavailable.</strong><p>${escapeHTML(message)} Please refresh and try again.</p></div>`};
const renderListPage = async type => { const root=document.getElementById(`${type}-list`); if(!root)return; const search=document.getElementById(`${type}-search`); const filter=document.getElementById(`${type}-category`); try { let entries=await loadFolder(`content/${type}`); entries.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)); const field=type==='blog'?'category':'section'; const cats=[...new Set(entries.map(e=>e[field]).filter(Boolean))].sort(); cats.forEach(cat=>{if(filter)filter.insertAdjacentHTML('beforeend',`<option value="${escapeHTML(cat)}">${escapeHTML(cat)}</option>`);const side=document.getElementById(`${type}-sidebar-categories`);if(side)side.insertAdjacentHTML('beforeend',`<li><a href="#" data-category="${escapeHTML(cat)}">${escapeHTML(cat)}</a></li>`)}); const draw=()=>{const query=(search?.value||'').toLowerCase();const selected=filter?.value||'';const visible=entries.filter(e=>(!query||`${e.title} ${e.summary} ${e.body}`.toLowerCase().includes(query))&&(!selected||e[field]===selected));root.innerHTML=visible.length?visible.map((e,i)=>type==='blog'?`<article class="cms-card ${i===0?'featured':''}">${e.image?`<img class="cms-card-image" src="${escapeHTML(imageURL(e.image))}" alt="">`:'<div class="cms-card-image" aria-hidden="true"></div>'}<div class="cms-card-copy"><p class="post-meta">${escapeHTML(e.category||'Community')} <span>•</span> ${formatDate(e.date)}</p><h2>${escapeHTML(e.title||'Untitled')}</h2><p>${escapeHTML(e.summary||e.body.replace(/[#>*`]/g,'').slice(0,150))}</p><p class="byline">By ${escapeHTML(e.author||'Putrajaya Editorial Team')}</p><a class="text-link" href="blog-post.html?slug=${encodeURIComponent(e.slug)}">Read the story <span>↗</span></a></div></article>`:`<article class="wiki-entry"><div class="wiki-entry-number">${String(i+1).padStart(2,'0')}</div><div><p class="eyebrow">${escapeHTML(e.section||'Reference')}</p><h3><a href="wiki-article.html?slug=${encodeURIComponent(e.slug)}">${escapeHTML(e.title||'Untitled')}</a></h3><p>${escapeHTML(e.summary||e.body.replace(/[#>*`]/g,'').slice(0,180))}</p></div><a class="entry-arrow" href="wiki-article.html?slug=${encodeURIComponent(e.slug)}">↗</a></article>`).join(''):'<p class="empty-state">No articles match your search.</p>'}; search?.addEventListener('input',draw);filter?.addEventListener('change',draw);document.querySelectorAll(`[data-category]`).forEach(link=>link.addEventListener('click',event=>{event.preventDefault();if(filter)filter.value=link.dataset.category;draw()}));draw(); } catch(error){renderError(root,error.message)} };
const renderArticlePage = async type => { const root=document.getElementById('article-root');if(!root)return;const slug=new URLSearchParams(location.search).get('slug');if(!slug){root.innerHTML='<div class="content-error"><strong>Article not found.</strong><p>Return to the directory to choose an article.</p></div>';return}try{const entries=await loadFolder(`content/${type}`);const e=entries.find(item=>item.slug===slug);if(!e)throw new Error('That article could not be found.');root.innerHTML=`<article class="cms-article"><a class="back-link" href="${type}.html">← Back to ${type==='blog'?'Blog':'Wiki'}</a><p class="eyebrow">${escapeHTML(type==='blog'?e.category||'Community':e.section||'Reference')}</p><h1>${escapeHTML(e.title||'Untitled')}</h1><p class="article-meta">${type==='blog'?`By ${escapeHTML(e.author||'Putrajaya Editorial Team')} · ${formatDate(e.date)}`:'Putrajaya of Roblox Wiki'}</p>${e.image?`<img class="article-cover" src="${escapeHTML(imageURL(e.image))}" alt="">`:''}<div class="article-body">${markdownToHTML(e.body)}</div></article>`}catch(error){renderError(root,error.message)}};
const initializeTheme = () => { const theme=document.querySelector('.theme-toggle');const saved=localStorage.getItem('putrajaya-theme');if(saved==='dark')document.body.classList.add('dark-mode');const sync=()=>{const dark=document.body.classList.contains('dark-mode');if(theme){theme.querySelector('.theme-icon').textContent=dark?'☀':'☾';theme.querySelector('.theme-label').textContent=dark?'Light':'Dark';theme.setAttribute('aria-label',dark?'Switch to light mode':'Switch to dark mode')}};theme?.addEventListener('click',()=>{document.body.classList.toggle('dark-mode');localStorage.setItem('putrajaya-theme',document.body.classList.contains('dark-mode')?'dark':'light');sync()});sync();const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav-links');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open?'true':'false')})};
const initializeReveal = () => { const items=[...document.querySelectorAll('.reveal')]; if(!items.length)return; if(!('IntersectionObserver' in window)){items.forEach(item=>item.classList.add('is-visible'));return}const observer=new IntersectionObserver((entries,obs)=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');obs.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -40px'});items.forEach(item=>observer.observe(item)); };
document.addEventListener('DOMContentLoaded',()=>{initializeTheme();initializeReveal();renderListPage('blog');renderListPage('wiki');renderArticlePage(document.body.dataset.articlePage)});
